### PR TITLE
Basic dropdowns and navigation working

### PR DESCRIPTION
**Pull request by deshipu**

### CODE REVIEW

**Comment by deshipu** [comment]
I'm not sure I got the context selector right, please verify. I had to guess what would happen with partial selections.

**Comment by jcoufal** [comment]
Thank you very much Radomir, this is amazingly great start and I have few comments for improvements:
- Context Selectors (Project + My Domain...)
  - On click, the menu appears (correct)
  - On click anywhere outside the context menu, the menu will get closed (so not just on click to the dropdown_trigger, but anywhere outside the context menu)
  - On click, the highest item .dropdown.selector gets the active class, so I we can change style for it. Disappears based on the 2nd point (click outside)
  - In My Domain..., there needs to be 2 states
    - one is 'active' for items which are currently selected (they are mentioned in the label of the dropdown) - so it stays active for the whole time, until user really change the domain by choosing (clicking) on some other)
    - second is 'hovered' for item which is being inspected (so it was hovered and pulled right particular context submenu)
  - If 'Other Domain' is not selected and I hover it, I shouldn't have got 3rd level items (regions) available. They load when I hover 'Other Other Project'. You can imagine this as loading lists. To get 2nd level I need to know what I have chosen from the first one. I cannot inspect 3rd level if I don't have hovered (chosen) the second level. If it is active item, I can see all 3 levels, until I hover some other part.
  - When I change Project/Admin, it should reflect in the top label. The same for Domain, Project, Region, it is triple, which I am selecting. So for example, if I choose Region B, the top label should show me 'Other Domain . Other Other Project . Region B'
- Can you add 'h1' for all pages, please, so it reflects their name by name in the navigation?
- The hover for Access & Security works only until I select some item from menu, when I 'change page', the dropdown stops working
- I will send you the information architecture in e-mail to capture better the navigation 2nd level.

One more time, thanks a lot for helping with this

**Comment by deshipu** [comment]
I fixed the problems, please take a look again when you have a moment.

**Comment by jcoufal** [comment]
Excellent, thank you very much, I'll continue to build on top of that.

**Pull request merged**
